api = "0.7"

[buildpack]
  description = "A custom Cloud Native Buildpack with an order definition suitable for Java applications on Azure"
  homepage = "https://github.com/devansha-optimus"  # Replace with your repo URL
  id = "com.devansh.buildpacks/java-azure"             # Custom ID
  keywords = ["java", "composite", "azure"]
  name = "Devansh Buildpack for Azure Java"
  version = "1.0.0"                                     # Use SemVer

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://www.apache.org/licenses/LICENSE-2.0"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "buildpack.toml"]

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.9.0"

  [[order.group]]
    id = "paketo-buildpacks/microsoft-openjdk"
    version = "4.0.1"

  [[order.group]]
    id = "paketo-buildpacks/yarn"
    optional = true
    version = "1.3.22"

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    optional = true
    version = "5.1.1"

  [[order.group]]
    id = "paketo-buildpacks/syft"
    optional = true
    version = "2.6.1"

  [[order.group]]
    id = "paketo-buildpacks/leiningen"
    optional = true
    version = "4.11.0"

  [[order.group]]
    id = "paketo-buildpacks/clojure-tools"
    optional = true
    version = "2.14.1"

  [[order.group]]
    id = "paketo-buildpacks/gradle"
    optional = true
    version = "7.15.2"

  [[order.group]]
    id = "paketo-buildpacks/maven"
    optional = true
    version = "6.19.2"

  [[order.group]]
    id = "paketo-buildpacks/sbt"
    optional = true
    version = "6.17.4"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "3.3.1"

  [[order.group]]
    id = "paketo-buildpacks/executable-jar"
    optional = true
    version = "6.12.0"

  [[order.group]]
    id = "paketo-buildpacks/apache-tomcat"
    optional = true
    version = "8.4.1"

  [[order.group]]
    id = "paketo-buildpacks/apache-tomee"
    optional = true
    version = "1.11.0"

  [[order.group]]
    id = "paketo-buildpacks/liberty"
    optional = true
    version = "4.4.1"

  [[order.group]]
    id = "paketo-buildpacks/dist-zip"
    optional = true
    version = "5.9.0"

  [[order.group]]
    id = "paketo-buildpacks/spring-boot"
    optional = true
    version = "5.32.0"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.10.2"

  [[order.group]]
    id = "paketo-buildpacks/jattach"
    optional = true
    version = "1.9.0"

  [[order.group]]
    id = "paketo-buildpacks/azure-application-insights"
    optional = true
    version = "5.23.0"

  [[order.group]]
    id = "paketo-buildpacks/datadog"
    optional = true
    version = "5.27.1"

  [[order.group]]
    id = "paketo-buildpacks/java-memory-assistant"
    optional = true
    version = "1.7.0"

  [[order.group]]
    id = "paketo-buildpacks/encrypt-at-rest"
    optional = true
    version = "4.8.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.8.0"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.8.0"
